### ISSUE TITLE
Juju 2.5-rc1 doesn't work as CloudFacade has no attribute 'UpdateCredentials'

### ISSUE THREAD

**Issue by ajkavanagh** [juju/python-libjuju#280]
It looks like (according to my small investigation) that UpdateCredentials has been renamed/changed to `UpdateCredentialsCheckModels`

```
$ juju version
2.5-rc1-bionic-amd64

$ functest-run-suite --keep-model -b trusty-icehouse 
Traceback (most recent call last):
  File "/home/ubuntu/charms/non-reactive/tox-ceph-osd/func-smoke/bin/functest-run-suite", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/charms/non-reactive/tox-ceph-osd/func-smoke/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 129, in main
    bundle=args.bundle)
  File "/home/ubuntu/charms/non-reactive/tox-ceph-osd/func-smoke/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 55, in func_test_runner
    prepare.prepare(model_name)
  File "/home/ubuntu/charms/non-reactive/tox-ceph-osd/func-smoke/lib/python3.6/site-packages/zaza/charm_lifecycle/prepare.py", line 93, in prepare
    zaza.controller.add_model(model_name, config=get_model_settings())
  File "/home/ubuntu/charms/non-reactive/tox-ceph-osd/func-smoke/lib/python3.6/site-packages/zaza/__init__.py", line 44, in _wrapper
    return run(_run_it())
  File "/home/ubuntu/charms/non-reactive/tox-ceph-osd/func-smoke/lib/python3.6/site-packages/zaza/__init__.py", line 32, in run
    return task.result()
  File "/home/ubuntu/charms/non-reactive/tox-ceph-osd/func-smoke/lib/python3.6/site-packages/zaza/__init__.py", line 43, in _run_it
    return await f(*args, **kwargs)
  File "/home/ubuntu/charms/non-reactive/tox-ceph-osd/func-smoke/lib/python3.6/site-packages/zaza/controller.py", line 34, in async_add_model
    model = await controller.add_model(model_name, config=config)
  File "/home/ubuntu/charms/non-reactive/tox-ceph-osd/func-smoke/lib/python3.6/site-packages/juju/controller.py", line 256, in add_model
    owner=owner)
  File "/home/ubuntu/charms/non-reactive/tox-ceph-osd/func-smoke/lib/python3.6/site-packages/juju/controller.py", line 220, in add_credential
    await cloud_facade.UpdateCredentials([
AttributeError: 'CloudFacade' object has no attribute 'UpdateCredentials'
```

This works fine on Juju 2.4.7 (for example).

**Comment by wallyworld** [comment]
There's a new version of the CloudAPI facade in Juju 2.5. 
Version 2 of the facade (in 2.4.7) uses UpdateCredentials
Version 3 of the facade (in 2.5) uses UpdateCredentialsCheckModels

The client library needs to call the correct API depending on the facade version available.

**Comment by ycliuhw** [comment]
a fix for this, anyone could help to review? or FYI @johnsca 
Thanks!

**Comment by wallyworld** [comment]
fixed in #281
