### ISSUE TITLE
regression: 'str' object has no attribute 'get' in application.set_config()

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#545]
https://github.com/juju/python-libjuju/blob/6face2a89af7669f45590929261f6235c35e13ef/juju/application.py#L522

The change introduced in #540 causes the following error with strings:
```sh
   File "/home/runner/work/lma-light-bundle/lma-light-bundle/tests/integration/test_bundle.py", line 89, in test_build_and_deploy
    await ops_test.model.applications["alertmanager"].set_config(
  File "/home/runner/work/lma-light-bundle/lma-light-bundle/.tox/integration/lib/python3.8/site-packages/juju/application.py", line 522, in set_config
    if v.get('value') is not None:
AttributeError: 'str' object has no attribute 'get'
```
Full log:
https://github.com/canonical/lma-light-bundle/runs/3625174791?check_suite_focus=true#step:4:161

**Comment by sed-i** [comment]
@cderici could you please take a look?

**Comment by juanmanuel-tirado** [comment]
This issue should be fixed after merging #544
